# Site settings
author: Darin "Gadol" Lee
title: Closed Mandibles Don't Get Fed
header-img: img/home-bg.png
email: darinleenavy@gmail.com
copyright_name: Darin "Gadol" Lee
description: > # this means to ignore newlines until "baseurl:"
  Life Through A Submariner's Eyes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  darinleejr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
